#!/usr/bin/env bash
# transfer files

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# disable strict host key

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# checking if the execvution was a sucess or not

if [ $? -eq 0 ]; then
	echo "File is sucessfully transferred"
else
	echo "File not transferred"
fi
