#!/usr/bin/env bash
# prints bad luck numbers

iter=1

while [ $iter -le 10 ]; do
	if [ $iter -eq 4 ]
	then
		echo "bad luck"
	elif [ $iter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	iter=$((iter + 1))
done
