#!/usr/bin/env bash
# count hours

hour=0
minutes=1

while [ $hour -le 12 ]; do
	echo "hour: $hour"
	while [ $minutes -le 59 ]; do
		echo "$minutes"
		(( minutes++ ))
	done
	(( hour++ ))
	minutes=1
done
